/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freefirfiltergenerator;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FileWriter;
import java.io.File;
import java.io.BufferedWriter;
import java.io.IOException;

/**
 *
 * @author Jean
 */
public class FreeFirFilterGeneratorForm extends javax.swing.JFrame {

    /**
     * Creates new form FreeFirFilterGeneratorForm
     */
    public FreeFirFilterGeneratorForm() {
        initComponents();
        checkFiltersMaxFcValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jComboBox1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabelSamplingFrequency = new javax.swing.JLabel();
        jComboBoxSamplingFrequency = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabelWindowing = new javax.swing.JLabel();
        jComboBoxWindowing = new javax.swing.JComboBox();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabelFilterType = new javax.swing.JLabel();
        jComboBoxFilterType = new javax.swing.JComboBox();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabelFilterLength = new javax.swing.JLabel();
        jSpinnerFilterLength = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabelLatency = new javax.swing.JLabel();
        jLabelLatencyValue = new javax.swing.JLabel();
        jLabelLatencyUnit = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanelLowPass = new javax.swing.JPanel();
        jLabelLowPassFc = new javax.swing.JLabel();
        jSpinnerLowPassFc = new javax.swing.JSpinner();
        jLabelLowPassOrder = new javax.swing.JLabel();
        jSpinnerLowPassOrder = new javax.swing.JSpinner();
        jPanelHighPass = new javax.swing.JPanel();
        jLabelHighPassFc = new javax.swing.JLabel();
        jSpinnerHighPassFc = new javax.swing.JSpinner();
        jLabelHighPassOrder = new javax.swing.JLabel();
        jSpinnerHighPassOrder = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuSaveFilterImpulseResponse = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuExit = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setLayout(new java.awt.GridLayout(5, 3, 10, 10));

        jLabelSamplingFrequency.setLabelFor(jComboBoxSamplingFrequency);
        jLabelSamplingFrequency.setText("Sampling frequency");
        jPanel3.add(jLabelSamplingFrequency);

        jComboBoxSamplingFrequency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "44100", "48000", "88200", "96000", "192000" }));
        jComboBoxSamplingFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSamplingFrequencyActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxSamplingFrequency);

        jLabel1.setText("Hz");
        jPanel3.add(jLabel1);

        jLabelWindowing.setLabelFor(jComboBoxWindowing);
        jLabelWindowing.setText("Windowing");
        jPanel3.add(jLabelWindowing);

        jComboBoxWindowing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rectangular (none)" }));
        jPanel3.add(jComboBoxWindowing);
        jPanel3.add(filler3);

        jLabelFilterType.setLabelFor(jComboBoxFilterType);
        jLabelFilterType.setText("Filter type");
        jPanel3.add(jLabelFilterType);

        jComboBoxFilterType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Allpass", "Lowpass", "Highpass", "Bandpass" }));
        jComboBoxFilterType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFilterTypeActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxFilterType);
        jPanel3.add(filler4);

        jLabelFilterLength.setLabelFor(jSpinnerFilterLength);
        jLabelFilterLength.setText("Filter length");
        jPanel3.add(jLabelFilterLength);

        jSpinnerFilterLength.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2), Integer.valueOf(2), null, Integer.valueOf(1)));
        jPanel3.add(jSpinnerFilterLength);

        jLabel2.setText("samples");
        jPanel3.add(jLabel2);

        jLabelLatency.setLabelFor(jLabelLatencyValue);
        jLabelLatency.setText("Time delay");
        jPanel3.add(jLabelLatency);

        jLabelLatencyValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLatencyValue.setText("0");
        jPanel3.add(jLabelLatencyValue);

        jLabelLatencyUnit.setText("ms");
        jPanel3.add(jLabelLatencyUnit);

        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        jPanelLowPass.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jLabelLowPassFc.setText("Lowpass fc");
        jPanelLowPass.add(jLabelLowPassFc);

        jSpinnerLowPassFc.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(1.0d), null, Double.valueOf(1.0d)));
        jSpinnerLowPassFc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerLowPassFcStateChanged(evt);
            }
        });
        jPanelLowPass.add(jSpinnerLowPassFc);

        jLabelLowPassOrder.setText("Lowpass order");
        jPanelLowPass.add(jLabelLowPassOrder);

        jSpinnerLowPassOrder.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jPanelLowPass.add(jSpinnerLowPassOrder);

        jPanel4.add(jPanelLowPass);

        jPanelHighPass.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jLabelHighPassFc.setText("Highpass fc");
        jPanelHighPass.add(jLabelHighPassFc);

        jSpinnerHighPassFc.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(1.0d)));
        jSpinnerHighPassFc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerHighPassFcStateChanged(evt);
            }
        });
        jPanelHighPass.add(jSpinnerHighPassFc);

        jLabelHighPassOrder.setText("Highpass order");
        jPanelHighPass.add(jLabelHighPassOrder);

        jSpinnerHighPassOrder.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(4), Integer.valueOf(1), null, Integer.valueOf(1)));
        jPanelHighPass.add(jSpinnerHighPassOrder);

        jPanel4.add(jPanelHighPass);

        jMenuFile.setText("File");

        jMenuSaveFilterImpulseResponse.setText("Save filter impulse response");
        jMenuSaveFilterImpulseResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveFilterImpulseResponseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuSaveFilterImpulseResponse);
        jMenuFile.add(jSeparator1);

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuExit);

        jMenuBar1.add(jMenuFile);

        jMenuAbout.setText("About");
        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSamplingFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSamplingFrequencyActionPerformed
        checkFiltersMaxFcValues();
    }//GEN-LAST:event_jComboBoxSamplingFrequencyActionPerformed

    private void jComboBoxFilterTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFilterTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFilterTypeActionPerformed

    private void jMenuSaveFilterImpulseResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveFilterImpulseResponseActionPerformed
        JFileChooser fs = new JFileChooser();
        fs.setDialogTitle("Save filter impulse response");
        fs.setFileFilter(new FileNameExtensionFilter("Text file (.txt)", ".txt"));
        int result = fs.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION) {
            // Save the file
            try {
                    double[] impulse;
                    double hpFc = (double)this.jSpinnerHighPassFc.getValue();
                    double lpFc = (double)this.jSpinnerLowPassFc.getValue();
                    int samplingRate = Integer.parseInt(this.jComboBoxSamplingFrequency.getSelectedItem().toString());
                    int hpOrder = (int)this.jSpinnerHighPassOrder.getValue();
                    int lpOrder = (int)this.jSpinnerLowPassOrder.getValue();
                    
                    int filterLength = (int)this.jSpinnerFilterLength.getValue();
                    String filterTypeString = this.jComboBoxFilterType.getSelectedItem().toString().toLowerCase();
                    if(filterTypeString.contains("lowpass")) {
                        System.out.println("Saving lowpass filter :");
                        System.out.println("Fc = " + lpFc + " hz");
                        
                        impulse = (new LowPassFilter(filterLength, samplingRate, lpFc, lpOrder)).getImpulse();
                    }
                    else if(filterTypeString.contains("highpass")) {
                        impulse = (new HighPassFilter(filterLength, samplingRate, hpFc, hpOrder)).getImpulse();
                    }
                    else if(filterTypeString.contains("bandpass")) {
                        impulse = (new BandPassFilter(filterLength, samplingRate, hpFc, hpOrder, lpFc, lpOrder)).getImpulse();
                    }
                    else {
                        return;
                    }
                    
                    File file = fs.getSelectedFile();
                    if(!file.getName().contains(".")) {
                        file = new File(fs.getSelectedFile() + ".txt");
                    }
                    
                    // if file doesnt exists, then create it
                    if (!file.exists()) {
                            file.createNewFile();
                    }

                    FileWriter fw = new FileWriter(file.getAbsoluteFile());
                    BufferedWriter bw = new BufferedWriter(fw);
                    for(int i = 0; i < impulse.length; ++i) {
                        bw.write(Double.toString(impulse[i]));
                        bw.newLine();
                    }
                    bw.close();

                    System.out.println("Done");

            } catch (IOException e) {
                    e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenuSaveFilterImpulseResponseActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        super.dispose();
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jSpinnerLowPassFcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerLowPassFcStateChanged
        checkFiltersMaxFcValues();
    }//GEN-LAST:event_jSpinnerLowPassFcStateChanged

    private void jSpinnerHighPassFcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerHighPassFcStateChanged
        checkFiltersMaxFcValues();
    }//GEN-LAST:event_jSpinnerHighPassFcStateChanged

    private void checkFiltersMaxFcValues() {
        double hpFcValue = (double)jSpinnerHighPassFc.getValue();
        double lpFcValue = (double)jSpinnerLowPassFc.getValue();
        double fcMax = Double.parseDouble(jComboBoxSamplingFrequency.getSelectedItem().toString())/2.0;
        
        // Set max fc values
        if(hpFcValue > fcMax) jSpinnerHighPassFc.setValue(fcMax);
        if(lpFcValue > fcMax) jSpinnerLowPassFc.setValue(fcMax);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FreeFirFilterGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FreeFirFilterGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FreeFirFilterGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FreeFirFilterGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FreeFirFilterGeneratorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxFilterType;
    private javax.swing.JComboBox jComboBoxSamplingFrequency;
    private javax.swing.JComboBox jComboBoxWindowing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFilterLength;
    private javax.swing.JLabel jLabelFilterType;
    private javax.swing.JLabel jLabelHighPassFc;
    private javax.swing.JLabel jLabelHighPassOrder;
    private javax.swing.JLabel jLabelLatency;
    private javax.swing.JLabel jLabelLatencyUnit;
    private javax.swing.JLabel jLabelLatencyValue;
    private javax.swing.JLabel jLabelLowPassFc;
    private javax.swing.JLabel jLabelLowPassOrder;
    private javax.swing.JLabel jLabelSamplingFrequency;
    private javax.swing.JLabel jLabelWindowing;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuSaveFilterImpulseResponse;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelHighPass;
    private javax.swing.JPanel jPanelLowPass;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSpinner jSpinnerFilterLength;
    private javax.swing.JSpinner jSpinnerHighPassFc;
    private javax.swing.JSpinner jSpinnerHighPassOrder;
    private javax.swing.JSpinner jSpinnerLowPassFc;
    private javax.swing.JSpinner jSpinnerLowPassOrder;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
