/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package freefirfiltergenerator;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FileWriter;
import java.io.File;
import java.io.BufferedWriter;
import java.io.IOException;
import javax.swing.text.DefaultFormatter;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.event.ChangeEvent;
import java.text.ParseException;

/**
 *
 * @author Jean
 */
public class FreeFirFilterGeneratorForm extends javax.swing.JFrame {

    /**
     * Creates new form FreeFirFilterGeneratorForm
     */
    public FreeFirFilterGeneratorForm() {
        initComponents();
        checkFiltersMaxFcValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jComboBox1 = new javax.swing.JComboBox();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabelSamplingFrequency = new javax.swing.JLabel();
        jComboBoxSamplingFrequency = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabelFilterType = new javax.swing.JLabel();
        jComboBoxFilterType1 = new javax.swing.JComboBox();
        jComboBoxFilterType2 = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jPanelHighPass = new javax.swing.JPanel();
        jLabelHighPassFc = new javax.swing.JLabel();
        jSpinnerHighPassFc = new javax.swing.JSpinner();
        jLabelHighPassOrder = new javax.swing.JLabel();
        jSpinnerHighPassOrder = new javax.swing.JSpinner();
        jLabelHighPassFilterPhase = new javax.swing.JLabel();
        jComboBoxHighPassFilterPhase = new javax.swing.JComboBox();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanelLowPass = new javax.swing.JPanel();
        jLabelLowPassFc = new javax.swing.JLabel();
        jSpinnerLowPassFc = new javax.swing.JSpinner();
        jLabelLowPassOrder = new javax.swing.JLabel();
        jSpinnerLowPassOrder = new javax.swing.JSpinner();
        jLabelLowPassFilterPhase = new javax.swing.JLabel();
        jComboBoxLowPassFilterPhase = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabelFilterLength = new javax.swing.JLabel();
        jSpinnerFilterLength = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabelLatency1 = new javax.swing.JLabel();
        jSpinnerFilterLength1 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabelLatency = new javax.swing.JLabel();
        jLabelLatencyValue = new javax.swing.JLabel();
        jLabelLatencyUnit = new javax.swing.JLabel();
        jLabelWindowing = new javax.swing.JLabel();
        jComboBoxWindowing = new javax.swing.JComboBox();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();
        jSpinnerWindowParam = new javax.swing.JSpinner();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuSaveFilterImpulseResponse = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuExit = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Free-FIR-Filter-Generator");
        setResizable(false);

        jPanel3.setLayout(new java.awt.GridLayout(2, 3, 10, 10));

        jLabelSamplingFrequency.setLabelFor(jComboBoxSamplingFrequency);
        jLabelSamplingFrequency.setText("Sampling frequency");
        jPanel3.add(jLabelSamplingFrequency);

        jComboBoxSamplingFrequency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "44100", "48000", "88200", "96000", "192000" }));
        jComboBoxSamplingFrequency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSamplingFrequencyActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxSamplingFrequency);

        jLabel1.setText("Hz");
        jPanel3.add(jLabel1);

        jLabelFilterType.setLabelFor(jComboBoxFilterType1);
        jLabelFilterType.setText("Filter type");
        jPanel3.add(jLabelFilterType);

        jComboBoxFilterType1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Allpass", "Lowpass", "Highpass", "Bandpass" }));
        jComboBoxFilterType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFilterType1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxFilterType1);

        jComboBoxFilterType2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Linkwitz-Riley", "Butterworth" }));
        jComboBoxFilterType2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFilterType2ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxFilterType2);

        jPanel4.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        jPanelHighPass.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        jLabelHighPassFc.setText("Highpass fc");
        jLabelHighPassFc.setEnabled(false);
        jPanelHighPass.add(jLabelHighPassFc);

        jSpinnerHighPassFc.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(1.0d), null, Double.valueOf(1.0d)));
        jSpinnerHighPassFc.setEnabled(false);
        jSpinnerHighPassFc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerHighPassFcStateChanged(evt);
            }
        });
        jPanelHighPass.add(jSpinnerHighPassFc);

        jLabelHighPassOrder.setText("Highpass order");
        jLabelHighPassOrder.setEnabled(false);
        jPanelHighPass.add(jLabelHighPassOrder);

        jSpinnerHighPassOrder.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinnerHighPassOrder.setEnabled(false);
        jPanelHighPass.add(jSpinnerHighPassOrder);

        jLabelHighPassFilterPhase.setText("Filter phase");
        jLabelHighPassFilterPhase.setEnabled(false);
        jPanelHighPass.add(jLabelHighPassFilterPhase);

        jComboBoxHighPassFilterPhase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Linear", "Minimal" }));
        jComboBoxHighPassFilterPhase.setEnabled(false);
        jPanelHighPass.add(jComboBoxHighPassFilterPhase);

        jPanel4.add(jPanelHighPass);
        jPanel4.add(filler5);

        jPanelLowPass.setLayout(new java.awt.GridLayout(3, 0, 10, 10));

        jLabelLowPassFc.setText("Lowpass fc");
        jLabelLowPassFc.setEnabled(false);
        jPanelLowPass.add(jLabelLowPassFc);

        jSpinnerLowPassFc.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(1.0d), null, Double.valueOf(1.0d)));
        jSpinnerLowPassFc.setEnabled(false);
        jSpinnerLowPassFc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerLowPassFcStateChanged(evt);
            }
        });
        jPanelLowPass.add(jSpinnerLowPassFc);

        jLabelLowPassOrder.setText("Lowpass order");
        jLabelLowPassOrder.setEnabled(false);
        jPanelLowPass.add(jLabelLowPassOrder);

        jSpinnerLowPassOrder.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        jSpinnerLowPassOrder.setEnabled(false);
        jPanelLowPass.add(jSpinnerLowPassOrder);

        jLabelLowPassFilterPhase.setText("Filter phase");
        jLabelLowPassFilterPhase.setEnabled(false);
        jPanelLowPass.add(jLabelLowPassFilterPhase);

        jComboBoxLowPassFilterPhase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Linear", "Minimal" }));
        jComboBoxLowPassFilterPhase.setEnabled(false);
        jPanelLowPass.add(jComboBoxLowPassFilterPhase);

        jPanel4.add(jPanelLowPass);

        jPanel1.setLayout(new java.awt.GridLayout(5, 3));

        jLabelFilterLength.setLabelFor(jSpinnerFilterLength);
        jLabelFilterLength.setText("Filter length (in samples)");
        jPanel1.add(jLabelFilterLength);

        jSpinnerFilterLength.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2), Integer.valueOf(2), null, Integer.valueOf(1)));
        jSpinnerFilterLength.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerFilterLengthStateChanged(evt);
            }
        });
        jPanel1.add(jSpinnerFilterLength);

        jButton1.setText("Auto suggest");
        jPanel1.add(jButton1);

        jLabelLatency1.setLabelFor(jLabelLatencyValue);
        jLabelLatency1.setText("Fiilter group delay (in samples)");
        jPanel1.add(jLabelLatency1);

        jSpinnerFilterLength1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2), Integer.valueOf(2), null, Integer.valueOf(1)));
        jSpinnerFilterLength1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerFilterLength1StateChanged(evt);
            }
        });
        jPanel1.add(jSpinnerFilterLength1);

        jButton2.setText("Auto suggest");
        jPanel1.add(jButton2);

        jLabelLatency.setLabelFor(jLabelLatencyValue);
        jLabelLatency.setText("Signal delay estimation");
        jPanel1.add(jLabelLatency);

        jLabelLatencyValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLatencyValue.setText("0");
        jPanel1.add(jLabelLatencyValue);

        jLabelLatencyUnit.setText(" ms");
        jPanel1.add(jLabelLatencyUnit);

        jLabelWindowing.setLabelFor(jComboBoxWindowing);
        jLabelWindowing.setText("Windowing");
        jPanel1.add(jLabelWindowing);

        jComboBoxWindowing.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rectangular (none)", "Triangular", "Welch", "Hanning", "Hamming", "Blackman", "Nuttall", "Blackman-Nuttall", "Blackman-Harris", "Flat top", "Gaussian*", "Tukey*", "Planck-Taper*", "DPSS/Slepian*", "Kaiser*", "Dolph–Chebyshev*", "Ultraspherical*", "Exponential/Poisson*", "Bartlett–Hann*", "Planck–Bessel*", "Hann-Poisson*", "Sinc/Lanczos*", " " }));
        jPanel1.add(jComboBoxWindowing);
        jPanel1.add(filler2);

        jLabel2.setText("Window parameter");
        jPanel1.add(jLabel2);

        jSpinnerWindowParam.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.0d, 1.0d, 0.05d));
        jSpinnerWindowParam.setEnabled(false);
        jPanel1.add(jSpinnerWindowParam);
        jPanel1.add(filler4);

        jMenuFile.setText("File");
        jMenuFile.setDelay(10);
        jMenuFile.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenuFileStateChanged(evt);
            }
        });

        jMenuSaveFilterImpulseResponse.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSaveFilterImpulseResponse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save-as-icon20.png"))); // NOI18N
        jMenuSaveFilterImpulseResponse.setText("Save filter impulse response");
        jMenuSaveFilterImpulseResponse.setPreferredSize(new java.awt.Dimension(341, 24));
        jMenuSaveFilterImpulseResponse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSaveFilterImpulseResponseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuSaveFilterImpulseResponse);
        jMenuFile.add(jSeparator1);

        jMenuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log-out-icon20.png"))); // NOI18N
        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuExit);

        jMenuBar1.add(jMenuFile);

        jMenuAbout.setText("About");
        jMenuBar1.add(jMenuAbout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxSamplingFrequencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSamplingFrequencyActionPerformed
        checkFiltersMaxFcValues();
        setFilterLatencyValue();
    }//GEN-LAST:event_jComboBoxSamplingFrequencyActionPerformed

    private void jComboBoxFilterType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFilterType1ActionPerformed
        String filterTypeString = this.jComboBoxFilterType1.getSelectedItem().toString().toLowerCase();
        if(filterTypeString.contains("allpass")) {
            setLowPassFilterEnabled(false);
            setHighPassFilterEnabled(false);
        }
        else if(filterTypeString.contains("highpass")) {
            setLowPassFilterEnabled(false);
            setHighPassFilterEnabled(true);
        }
        else if(filterTypeString.contains("lowpass")) {
            setLowPassFilterEnabled(true);
            setHighPassFilterEnabled(false);
        }
        else if(filterTypeString.contains("bandpass")) {
            setLowPassFilterEnabled(true);
            setHighPassFilterEnabled(true);
        }
        else {
            // Unknown filter type
        }
    }//GEN-LAST:event_jComboBoxFilterType1ActionPerformed

    private void jMenuSaveFilterImpulseResponseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSaveFilterImpulseResponseActionPerformed
        try {
            this.jSpinnerFilterLength.commitEdit();
            this.jSpinnerHighPassFc.commitEdit();
            this.jSpinnerHighPassOrder.commitEdit();
            this.jSpinnerLowPassFc.commitEdit();
            this.jSpinnerLowPassOrder.commitEdit();
        }
        catch(ParseException e) {
            
        }
        
        JFileChooser fs = new JFileChooser();
        fs.setDialogTitle("Save filter impulse response");
        fs.setFileFilter(new FileNameExtensionFilter("Text file (.txt)", ".txt"));
        int result = fs.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION) {
            // Save the file
            try {
                    double[] impulse;
                    double hpFc = (double)this.jSpinnerHighPassFc.getValue();
                    double lpFc = (double)this.jSpinnerLowPassFc.getValue();
                    int samplingRate = Integer.parseInt(this.jComboBoxSamplingFrequency.getSelectedItem().toString());
                    int hpOrder = (int)this.jSpinnerHighPassOrder.getValue();
                    int lpOrder = (int)this.jSpinnerLowPassOrder.getValue();
                    
                    int filterLength = (int)this.jSpinnerFilterLength.getValue();
                    String filterTypeString = this.jComboBoxFilterType1.getSelectedItem().toString().toLowerCase();
                    if(filterTypeString.contains("lowpass")) {
                        System.out.println("Saving lowpass filter :");
                        System.out.println("Fc = " + lpFc + " hz");
                        
                        impulse = (new LowPassFilter(filterLength, samplingRate, lpFc, lpOrder)).getImpulse();
                    }
                    else if(filterTypeString.contains("highpass")) {
                        impulse = (new HighPassFilter(filterLength, samplingRate, hpFc, hpOrder)).getImpulse();
                    }
                    else if(filterTypeString.contains("bandpass")) {
                        impulse = (new BandPassFilter(filterLength, samplingRate, hpFc, hpOrder, lpFc, lpOrder)).getImpulse();
                    }
                    else {
                        return;
                    }
                    
                    // Apply window if needed
                    String windowTypeString = this.jComboBoxWindowing.getSelectedItem().toString().toLowerCase();
                    
                    double[] window;
                    
                    if(windowTypeString.contains("rectangular")) {
                        window = Window.rectangular(impulse.length);
                    }
                    else if(windowTypeString.contains("triangular")) {
                        window = Window.triangular(impulse.length);
                    }
                    else if(windowTypeString.contains("welch")) {
                        window = Window.welch(impulse.length);
                    }
                    else if(windowTypeString.contains("hanning")) {
                        window = Window.hanning(impulse.length);
                    }
                    else if(windowTypeString.contains("hamming")) {
                        window = Window.hamming(impulse.length);
                    }
                    else if(windowTypeString.contains("blackman")) {
                        if(windowTypeString.contains("nuttall")) {
                            window = Window.blackman_nuttall(impulse.length);
                        }
                        else if(windowTypeString.contains("harris")) {
                            window = Window.blackman_harris(impulse.length);
                        }
                        else {
                            window = Window.blackman(impulse.length);
                        }
                    }
                    else if(windowTypeString.contains("nuttall")) {
                        window = Window.nuttall(impulse.length);
                    }
                    else if(windowTypeString.contains("flat top")) {
                        window = Window.flat_top(impulse.length);
                    }
                    else if(windowTypeString.contains("gaussian")) {
                        window = Window.gaussian(impulse.length, (double)this.jSpinnerWindowParam.getValue());
                    }
                    else if(windowTypeString.contains("tukey")) {
                        window = Window.tukey(impulse.length, (double)this.jSpinnerWindowParam.getValue());
                    }
                    else {
                        window = new double[impulse.length];
                        for(int i = 0; i < impulse.length; i++) {
                            window[i] = 0.0;
                        }
                    }
                    
                    for(int i = 0; i < impulse.length; i++) {
                        impulse[i] *= window[i];
                    }
                    
                    File file = fs.getSelectedFile();
                    if(!file.getName().contains(".")) {
                        file = new File(fs.getSelectedFile() + ".txt");
                    }
                    
                    // if file doesnt exists, then create it
                    if (!file.exists()) {
                            file.createNewFile();
                    }

                    FileWriter fw = new FileWriter(file.getAbsoluteFile());
                    BufferedWriter bw = new BufferedWriter(fw);
                    for(int i = 0; i < impulse.length; ++i) {
                        bw.write(Double.toString(impulse[i]));
                        bw.newLine();
                    }
                    bw.close();

                    System.out.println("Done");

            } catch (IOException e) {
                    e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenuSaveFilterImpulseResponseActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        super.dispose();
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void jSpinnerLowPassFcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerLowPassFcStateChanged
        checkFiltersMaxFcValues();
    }//GEN-LAST:event_jSpinnerLowPassFcStateChanged

    private void jSpinnerHighPassFcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerHighPassFcStateChanged
        checkFiltersMaxFcValues();
    }//GEN-LAST:event_jSpinnerHighPassFcStateChanged

    private void jSpinnerFilterLengthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerFilterLengthStateChanged
        setFilterLatencyValue();
    }//GEN-LAST:event_jSpinnerFilterLengthStateChanged

    private void jMenuFileStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenuFileStateChanged
        try {
            this.jSpinnerFilterLength.commitEdit();
            this.jSpinnerHighPassFc.commitEdit();
            this.jSpinnerHighPassOrder.commitEdit();
            this.jSpinnerLowPassFc.commitEdit();
            this.jSpinnerLowPassOrder.commitEdit();
        }
        catch(ParseException e) {
            
        }
    }//GEN-LAST:event_jMenuFileStateChanged

    private void jSpinnerFilterLength1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerFilterLength1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jSpinnerFilterLength1StateChanged

    private void jComboBoxFilterType2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFilterType2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFilterType2ActionPerformed

    private void checkFiltersMaxFcValues() {
        double hpFcValue = (double)jSpinnerHighPassFc.getValue();
        double lpFcValue = (double)jSpinnerLowPassFc.getValue();
        double fcMax = Double.parseDouble(jComboBoxSamplingFrequency.getSelectedItem().toString())/2.0;
        /*JComponent comp = this.jSpinnerFilterLength.getEditor();
        JFormattedTextField field = (JFormattedTextField) comp.getComponent(0);
        DefaultFormatter formatter = (DefaultFormatter) field.getFormatter();
        formatter.setCommitsOnValidEdit(true);*/
    
        // Set max fc values
        if(hpFcValue > fcMax) jSpinnerHighPassFc.setValue(fcMax);
        if(lpFcValue > fcMax) jSpinnerLowPassFc.setValue(fcMax);
    }
    
    private void setFilterLatencyValue() {
        double samplingRate = Double.parseDouble(this.jComboBoxSamplingFrequency.getSelectedItem().toString());
        int filterLength = (int)this.jSpinnerFilterLength.getValue();
        double filterLatency = (filterLength-1.0)*1000.0/(2.0*samplingRate);
        this.jLabelLatencyValue.setText(String.format("%1$,.4f", filterLatency));
    }
    
    private void setLowPassFilterEnabled(boolean value) {
        this.jSpinnerLowPassFc.setEnabled(value);
        this.jSpinnerLowPassOrder.setEnabled(value);
        this.jComboBoxLowPassFilterPhase.setEnabled(value);
        this.jLabelLowPassFc.setEnabled(value);
        this.jLabelLowPassOrder.setEnabled(value);
        this.jLabelLowPassFilterPhase.setEnabled(value);
    }
    
    private void setHighPassFilterEnabled(boolean value) {
        this.jSpinnerHighPassFc.setEnabled(value);
        this.jSpinnerHighPassOrder.setEnabled(value);
        this.jComboBoxHighPassFilterPhase.setEnabled(value);
        this.jLabelHighPassFc.setEnabled(value);
        this.jLabelHighPassOrder.setEnabled(value);
        this.jLabelHighPassFilterPhase.setEnabled(value);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FreeFirFilterGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FreeFirFilterGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FreeFirFilterGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FreeFirFilterGeneratorForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FreeFirFilterGeneratorForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxFilterType1;
    private javax.swing.JComboBox jComboBoxFilterType2;
    private javax.swing.JComboBox jComboBoxHighPassFilterPhase;
    private javax.swing.JComboBox jComboBoxLowPassFilterPhase;
    private javax.swing.JComboBox jComboBoxSamplingFrequency;
    private javax.swing.JComboBox jComboBoxWindowing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFilterLength;
    private javax.swing.JLabel jLabelFilterType;
    private javax.swing.JLabel jLabelHighPassFc;
    private javax.swing.JLabel jLabelHighPassFilterPhase;
    private javax.swing.JLabel jLabelHighPassOrder;
    private javax.swing.JLabel jLabelLatency;
    private javax.swing.JLabel jLabelLatency1;
    private javax.swing.JLabel jLabelLatencyUnit;
    private javax.swing.JLabel jLabelLatencyValue;
    private javax.swing.JLabel jLabelLowPassFc;
    private javax.swing.JLabel jLabelLowPassFilterPhase;
    private javax.swing.JLabel jLabelLowPassOrder;
    private javax.swing.JLabel jLabelSamplingFrequency;
    private javax.swing.JLabel jLabelWindowing;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuSaveFilterImpulseResponse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelHighPass;
    private javax.swing.JPanel jPanelLowPass;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinnerFilterLength;
    private javax.swing.JSpinner jSpinnerFilterLength1;
    private javax.swing.JSpinner jSpinnerHighPassFc;
    private javax.swing.JSpinner jSpinnerHighPassOrder;
    private javax.swing.JSpinner jSpinnerLowPassFc;
    private javax.swing.JSpinner jSpinnerLowPassOrder;
    private javax.swing.JSpinner jSpinnerWindowParam;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
